package worktile.repository.model;

public class MenuAppoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.OPER_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String operPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.MENU_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String menuPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.MENU_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.PKID
     *
     * @return the value of WORKTILE.MENU_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.PKID
     *
     * @param pkid the value for WORKTILE.MENU_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.OPER_PKID
     *
     * @return the value of WORKTILE.MENU_APPOINT.OPER_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getOperPkid() {
        return operPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.OPER_PKID
     *
     * @param operPkid the value for WORKTILE.MENU_APPOINT.OPER_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setOperPkid(String operPkid) {
        this.operPkid = operPkid == null ? null : operPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.MENU_PKID
     *
     * @return the value of WORKTILE.MENU_APPOINT.MENU_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getMenuPkid() {
        return menuPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.MENU_PKID
     *
     * @param menuPkid the value for WORKTILE.MENU_APPOINT.MENU_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setMenuPkid(String menuPkid) {
        this.menuPkid = menuPkid == null ? null : menuPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.ARCHIVED_FLAG
     *
     * @return the value of WORKTILE.MENU_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for WORKTILE.MENU_APPOINT.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.CREATED_BY
     *
     * @return the value of WORKTILE.MENU_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.CREATED_BY
     *
     * @param createdBy the value for WORKTILE.MENU_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.CREATED_TIME
     *
     * @return the value of WORKTILE.MENU_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.CREATED_TIME
     *
     * @param createdTime the value for WORKTILE.MENU_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.LAST_UPD_BY
     *
     * @return the value of WORKTILE.MENU_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.LAST_UPD_BY
     *
     * @param lastUpdBy the value for WORKTILE.MENU_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.LAST_UPD_TIME
     *
     * @return the value of WORKTILE.MENU_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for WORKTILE.MENU_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.REMARK
     *
     * @return the value of WORKTILE.MENU_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.REMARK
     *
     * @param remark the value for WORKTILE.MENU_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.REC_VERSION
     *
     * @return the value of WORKTILE.MENU_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.REC_VERSION
     *
     * @param recVersion the value for WORKTILE.MENU_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.MENU_APPOINT.TID
     *
     * @return the value of WORKTILE.MENU_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.MENU_APPOINT.TID
     *
     * @param tid the value for WORKTILE.MENU_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}