package worktile.repository.model;

public class Ptlogicact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String logiccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String logicclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String logicmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String logicdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String logicenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.PTLOGICACT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.PKID
     *
     * @return the value of WORKTILE.PTLOGICACT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.PKID
     *
     * @param pkid the value for WORKTILE.PTLOGICACT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.LOGICCODE
     *
     * @return the value of WORKTILE.PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLogiccode() {
        return logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.LOGICCODE
     *
     * @param logiccode the value for WORKTILE.PTLOGICACT.LOGICCODE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLogiccode(String logiccode) {
        this.logiccode = logiccode == null ? null : logiccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.LOGICCLASS
     *
     * @return the value of WORKTILE.PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLogicclass() {
        return logicclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.LOGICCLASS
     *
     * @param logicclass the value for WORKTILE.PTLOGICACT.LOGICCLASS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLogicclass(String logicclass) {
        this.logicclass = logicclass == null ? null : logicclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.LOGICMETHOD
     *
     * @return the value of WORKTILE.PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLogicmethod() {
        return logicmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.LOGICMETHOD
     *
     * @param logicmethod the value for WORKTILE.PTLOGICACT.LOGICMETHOD
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLogicmethod(String logicmethod) {
        this.logicmethod = logicmethod == null ? null : logicmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.LOGICDESC
     *
     * @return the value of WORKTILE.PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLogicdesc() {
        return logicdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.LOGICDESC
     *
     * @param logicdesc the value for WORKTILE.PTLOGICACT.LOGICDESC
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLogicdesc(String logicdesc) {
        this.logicdesc = logicdesc == null ? null : logicdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.LOGICENABLED
     *
     * @return the value of WORKTILE.PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLogicenabled() {
        return logicenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.LOGICENABLED
     *
     * @param logicenabled the value for WORKTILE.PTLOGICACT.LOGICENABLED
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLogicenabled(String logicenabled) {
        this.logicenabled = logicenabled == null ? null : logicenabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.PTLOGICACT.TID
     *
     * @return the value of WORKTILE.PTLOGICACT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.PTLOGICACT.TID
     *
     * @param tid the value for WORKTILE.PTLOGICACT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}