package worktile.repository.model;

import java.util.ArrayList;
import java.util.List;

public class PtmenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public PtmenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNull() {
            addCriterion("MENUID is null");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNotNull() {
            addCriterion("MENUID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuidEqualTo(String value) {
            addCriterion("MENUID =", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotEqualTo(String value) {
            addCriterion("MENUID <>", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThan(String value) {
            addCriterion("MENUID >", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThanOrEqualTo(String value) {
            addCriterion("MENUID >=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThan(String value) {
            addCriterion("MENUID <", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThanOrEqualTo(String value) {
            addCriterion("MENUID <=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLike(String value) {
            addCriterion("MENUID like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotLike(String value) {
            addCriterion("MENUID not like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidIn(List<String> values) {
            addCriterion("MENUID in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotIn(List<String> values) {
            addCriterion("MENUID not in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidBetween(String value1, String value2) {
            addCriterion("MENUID between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotBetween(String value1, String value2) {
            addCriterion("MENUID not between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIsNull() {
            addCriterion("PARENTMENUID is null");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIsNotNull() {
            addCriterion("PARENTMENUID is not null");
            return (Criteria) this;
        }

        public Criteria andParentmenuidEqualTo(String value) {
            addCriterion("PARENTMENUID =", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotEqualTo(String value) {
            addCriterion("PARENTMENUID <>", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidGreaterThan(String value) {
            addCriterion("PARENTMENUID >", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTMENUID >=", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLessThan(String value) {
            addCriterion("PARENTMENUID <", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLessThanOrEqualTo(String value) {
            addCriterion("PARENTMENUID <=", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidLike(String value) {
            addCriterion("PARENTMENUID like", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotLike(String value) {
            addCriterion("PARENTMENUID not like", value, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidIn(List<String> values) {
            addCriterion("PARENTMENUID in", values, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotIn(List<String> values) {
            addCriterion("PARENTMENUID not in", values, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidBetween(String value1, String value2) {
            addCriterion("PARENTMENUID between", value1, value2, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andParentmenuidNotBetween(String value1, String value2) {
            addCriterion("PARENTMENUID not between", value1, value2, "parentmenuid");
            return (Criteria) this;
        }

        public Criteria andMenulevelIsNull() {
            addCriterion("MENULEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMenulevelIsNotNull() {
            addCriterion("MENULEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMenulevelEqualTo(Integer value) {
            addCriterion("MENULEVEL =", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotEqualTo(Integer value) {
            addCriterion("MENULEVEL <>", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelGreaterThan(Integer value) {
            addCriterion("MENULEVEL >", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("MENULEVEL >=", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelLessThan(Integer value) {
            addCriterion("MENULEVEL <", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelLessThanOrEqualTo(Integer value) {
            addCriterion("MENULEVEL <=", value, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelIn(List<Integer> values) {
            addCriterion("MENULEVEL in", values, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotIn(List<Integer> values) {
            addCriterion("MENULEVEL not in", values, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelBetween(Integer value1, Integer value2) {
            addCriterion("MENULEVEL between", value1, value2, "menulevel");
            return (Criteria) this;
        }

        public Criteria andMenulevelNotBetween(Integer value1, Integer value2) {
            addCriterion("MENULEVEL not between", value1, value2, "menulevel");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNull() {
            addCriterion("ISLEAF is null");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNotNull() {
            addCriterion("ISLEAF is not null");
            return (Criteria) this;
        }

        public Criteria andIsleafEqualTo(Integer value) {
            addCriterion("ISLEAF =", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotEqualTo(Integer value) {
            addCriterion("ISLEAF <>", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThan(Integer value) {
            addCriterion("ISLEAF >", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThanOrEqualTo(Integer value) {
            addCriterion("ISLEAF >=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThan(Integer value) {
            addCriterion("ISLEAF <", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThanOrEqualTo(Integer value) {
            addCriterion("ISLEAF <=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafIn(List<Integer> values) {
            addCriterion("ISLEAF in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotIn(List<Integer> values) {
            addCriterion("ISLEAF not in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafBetween(Integer value1, Integer value2) {
            addCriterion("ISLEAF between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotBetween(Integer value1, Integer value2) {
            addCriterion("ISLEAF not between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andMenudescIsNull() {
            addCriterion("MENUDESC is null");
            return (Criteria) this;
        }

        public Criteria andMenudescIsNotNull() {
            addCriterion("MENUDESC is not null");
            return (Criteria) this;
        }

        public Criteria andMenudescEqualTo(String value) {
            addCriterion("MENUDESC =", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotEqualTo(String value) {
            addCriterion("MENUDESC <>", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescGreaterThan(String value) {
            addCriterion("MENUDESC >", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescGreaterThanOrEqualTo(String value) {
            addCriterion("MENUDESC >=", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLessThan(String value) {
            addCriterion("MENUDESC <", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLessThanOrEqualTo(String value) {
            addCriterion("MENUDESC <=", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescLike(String value) {
            addCriterion("MENUDESC like", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotLike(String value) {
            addCriterion("MENUDESC not like", value, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescIn(List<String> values) {
            addCriterion("MENUDESC in", values, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotIn(List<String> values) {
            addCriterion("MENUDESC not in", values, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescBetween(String value1, String value2) {
            addCriterion("MENUDESC between", value1, value2, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenudescNotBetween(String value1, String value2) {
            addCriterion("MENUDESC not between", value1, value2, "menudesc");
            return (Criteria) this;
        }

        public Criteria andMenulabelIsNull() {
            addCriterion("MENULABEL is null");
            return (Criteria) this;
        }

        public Criteria andMenulabelIsNotNull() {
            addCriterion("MENULABEL is not null");
            return (Criteria) this;
        }

        public Criteria andMenulabelEqualTo(String value) {
            addCriterion("MENULABEL =", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotEqualTo(String value) {
            addCriterion("MENULABEL <>", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelGreaterThan(String value) {
            addCriterion("MENULABEL >", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelGreaterThanOrEqualTo(String value) {
            addCriterion("MENULABEL >=", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLessThan(String value) {
            addCriterion("MENULABEL <", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLessThanOrEqualTo(String value) {
            addCriterion("MENULABEL <=", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelLike(String value) {
            addCriterion("MENULABEL like", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotLike(String value) {
            addCriterion("MENULABEL not like", value, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelIn(List<String> values) {
            addCriterion("MENULABEL in", values, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotIn(List<String> values) {
            addCriterion("MENULABEL not in", values, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelBetween(String value1, String value2) {
            addCriterion("MENULABEL between", value1, value2, "menulabel");
            return (Criteria) this;
        }

        public Criteria andMenulabelNotBetween(String value1, String value2) {
            addCriterion("MENULABEL not between", value1, value2, "menulabel");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIsNull() {
            addCriterion("TARGETMACHINE is null");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIsNotNull() {
            addCriterion("TARGETMACHINE is not null");
            return (Criteria) this;
        }

        public Criteria andTargetmachineEqualTo(String value) {
            addCriterion("TARGETMACHINE =", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotEqualTo(String value) {
            addCriterion("TARGETMACHINE <>", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineGreaterThan(String value) {
            addCriterion("TARGETMACHINE >", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineGreaterThanOrEqualTo(String value) {
            addCriterion("TARGETMACHINE >=", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLessThan(String value) {
            addCriterion("TARGETMACHINE <", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLessThanOrEqualTo(String value) {
            addCriterion("TARGETMACHINE <=", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineLike(String value) {
            addCriterion("TARGETMACHINE like", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotLike(String value) {
            addCriterion("TARGETMACHINE not like", value, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineIn(List<String> values) {
            addCriterion("TARGETMACHINE in", values, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotIn(List<String> values) {
            addCriterion("TARGETMACHINE not in", values, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineBetween(String value1, String value2) {
            addCriterion("TARGETMACHINE between", value1, value2, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andTargetmachineNotBetween(String value1, String value2) {
            addCriterion("TARGETMACHINE not between", value1, value2, "targetmachine");
            return (Criteria) this;
        }

        public Criteria andMenuactionIsNull() {
            addCriterion("MENUACTION is null");
            return (Criteria) this;
        }

        public Criteria andMenuactionIsNotNull() {
            addCriterion("MENUACTION is not null");
            return (Criteria) this;
        }

        public Criteria andMenuactionEqualTo(String value) {
            addCriterion("MENUACTION =", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotEqualTo(String value) {
            addCriterion("MENUACTION <>", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionGreaterThan(String value) {
            addCriterion("MENUACTION >", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionGreaterThanOrEqualTo(String value) {
            addCriterion("MENUACTION >=", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLessThan(String value) {
            addCriterion("MENUACTION <", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLessThanOrEqualTo(String value) {
            addCriterion("MENUACTION <=", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionLike(String value) {
            addCriterion("MENUACTION like", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotLike(String value) {
            addCriterion("MENUACTION not like", value, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionIn(List<String> values) {
            addCriterion("MENUACTION in", values, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotIn(List<String> values) {
            addCriterion("MENUACTION not in", values, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionBetween(String value1, String value2) {
            addCriterion("MENUACTION between", value1, value2, "menuaction");
            return (Criteria) this;
        }

        public Criteria andMenuactionNotBetween(String value1, String value2) {
            addCriterion("MENUACTION not between", value1, value2, "menuaction");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIsNull() {
            addCriterion("OPENWINDOW is null");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIsNotNull() {
            addCriterion("OPENWINDOW is not null");
            return (Criteria) this;
        }

        public Criteria andOpenwindowEqualTo(String value) {
            addCriterion("OPENWINDOW =", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotEqualTo(String value) {
            addCriterion("OPENWINDOW <>", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowGreaterThan(String value) {
            addCriterion("OPENWINDOW >", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowGreaterThanOrEqualTo(String value) {
            addCriterion("OPENWINDOW >=", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLessThan(String value) {
            addCriterion("OPENWINDOW <", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLessThanOrEqualTo(String value) {
            addCriterion("OPENWINDOW <=", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowLike(String value) {
            addCriterion("OPENWINDOW like", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotLike(String value) {
            addCriterion("OPENWINDOW not like", value, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowIn(List<String> values) {
            addCriterion("OPENWINDOW in", values, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotIn(List<String> values) {
            addCriterion("OPENWINDOW not in", values, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowBetween(String value1, String value2) {
            addCriterion("OPENWINDOW between", value1, value2, "openwindow");
            return (Criteria) this;
        }

        public Criteria andOpenwindowNotBetween(String value1, String value2) {
            addCriterion("OPENWINDOW not between", value1, value2, "openwindow");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIsNull() {
            addCriterion("WINDOWWIDTH is null");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIsNotNull() {
            addCriterion("WINDOWWIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andWindowwidthEqualTo(Integer value) {
            addCriterion("WINDOWWIDTH =", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotEqualTo(Integer value) {
            addCriterion("WINDOWWIDTH <>", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthGreaterThan(Integer value) {
            addCriterion("WINDOWWIDTH >", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("WINDOWWIDTH >=", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthLessThan(Integer value) {
            addCriterion("WINDOWWIDTH <", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthLessThanOrEqualTo(Integer value) {
            addCriterion("WINDOWWIDTH <=", value, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthIn(List<Integer> values) {
            addCriterion("WINDOWWIDTH in", values, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotIn(List<Integer> values) {
            addCriterion("WINDOWWIDTH not in", values, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthBetween(Integer value1, Integer value2) {
            addCriterion("WINDOWWIDTH between", value1, value2, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowwidthNotBetween(Integer value1, Integer value2) {
            addCriterion("WINDOWWIDTH not between", value1, value2, "windowwidth");
            return (Criteria) this;
        }

        public Criteria andWindowheightIsNull() {
            addCriterion("WINDOWHEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWindowheightIsNotNull() {
            addCriterion("WINDOWHEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWindowheightEqualTo(Integer value) {
            addCriterion("WINDOWHEIGHT =", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotEqualTo(Integer value) {
            addCriterion("WINDOWHEIGHT <>", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightGreaterThan(Integer value) {
            addCriterion("WINDOWHEIGHT >", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightGreaterThanOrEqualTo(Integer value) {
            addCriterion("WINDOWHEIGHT >=", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightLessThan(Integer value) {
            addCriterion("WINDOWHEIGHT <", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightLessThanOrEqualTo(Integer value) {
            addCriterion("WINDOWHEIGHT <=", value, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightIn(List<Integer> values) {
            addCriterion("WINDOWHEIGHT in", values, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotIn(List<Integer> values) {
            addCriterion("WINDOWHEIGHT not in", values, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightBetween(Integer value1, Integer value2) {
            addCriterion("WINDOWHEIGHT between", value1, value2, "windowheight");
            return (Criteria) this;
        }

        public Criteria andWindowheightNotBetween(Integer value1, Integer value2) {
            addCriterion("WINDOWHEIGHT not between", value1, value2, "windowheight");
            return (Criteria) this;
        }

        public Criteria andLevelidxIsNull() {
            addCriterion("LEVELIDX is null");
            return (Criteria) this;
        }

        public Criteria andLevelidxIsNotNull() {
            addCriterion("LEVELIDX is not null");
            return (Criteria) this;
        }

        public Criteria andLevelidxEqualTo(Integer value) {
            addCriterion("LEVELIDX =", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotEqualTo(Integer value) {
            addCriterion("LEVELIDX <>", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxGreaterThan(Integer value) {
            addCriterion("LEVELIDX >", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEVELIDX >=", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxLessThan(Integer value) {
            addCriterion("LEVELIDX <", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxLessThanOrEqualTo(Integer value) {
            addCriterion("LEVELIDX <=", value, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxIn(List<Integer> values) {
            addCriterion("LEVELIDX in", values, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotIn(List<Integer> values) {
            addCriterion("LEVELIDX not in", values, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxBetween(Integer value1, Integer value2) {
            addCriterion("LEVELIDX between", value1, value2, "levelidx");
            return (Criteria) this;
        }

        public Criteria andLevelidxNotBetween(Integer value1, Integer value2) {
            addCriterion("LEVELIDX not between", value1, value2, "levelidx");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("TID is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("TID is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(String value) {
            addCriterion("TID =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(String value) {
            addCriterion("TID <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(String value) {
            addCriterion("TID >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(String value) {
            addCriterion("TID >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(String value) {
            addCriterion("TID <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(String value) {
            addCriterion("TID <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLike(String value) {
            addCriterion("TID like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotLike(String value) {
            addCriterion("TID not like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<String> values) {
            addCriterion("TID in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<String> values) {
            addCriterion("TID not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(String value1, String value2) {
            addCriterion("TID between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(String value1, String value2) {
            addCriterion("TID not between", value1, value2, "tid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 13 14:57:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.PTMENU
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}