package worktile.repository.model;

public class RsTidKeys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.RS_TID_KEYS.PKID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.RS_TID_KEYS.TID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.RS_TID_KEYS.OPER_COUNTS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    private String operCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.RS_TID_KEYS.ES_KEY
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    private String esKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.RS_TID_KEYS.PKID
     *
     * @return the value of TASK.RS_TID_KEYS.PKID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.RS_TID_KEYS.PKID
     *
     * @param pkid the value for TASK.RS_TID_KEYS.PKID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.RS_TID_KEYS.TID
     *
     * @return the value of TASK.RS_TID_KEYS.TID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.RS_TID_KEYS.TID
     *
     * @param tid the value for TASK.RS_TID_KEYS.TID
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.RS_TID_KEYS.OPER_COUNTS
     *
     * @return the value of TASK.RS_TID_KEYS.OPER_COUNTS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public String getOperCounts() {
        return operCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.RS_TID_KEYS.OPER_COUNTS
     *
     * @param operCounts the value for TASK.RS_TID_KEYS.OPER_COUNTS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public void setOperCounts(String operCounts) {
        this.operCounts = operCounts == null ? null : operCounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.RS_TID_KEYS.ES_KEY
     *
     * @return the value of TASK.RS_TID_KEYS.ES_KEY
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public String getEsKey() {
        return esKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.RS_TID_KEYS.ES_KEY
     *
     * @param esKey the value for TASK.RS_TID_KEYS.ES_KEY
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    public void setEsKey(String esKey) {
        this.esKey = esKey == null ? null : esKey.trim();
    }
}