package worktile.repository.model;

import java.util.ArrayList;
import java.util.List;

public class WorktileAppointHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public WorktileAppointHisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIsNull() {
            addCriterion("INFO_PKID is null");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIsNotNull() {
            addCriterion("INFO_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoPkidEqualTo(String value) {
            addCriterion("INFO_PKID =", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotEqualTo(String value) {
            addCriterion("INFO_PKID <>", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidGreaterThan(String value) {
            addCriterion("INFO_PKID >", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_PKID >=", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLessThan(String value) {
            addCriterion("INFO_PKID <", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLessThanOrEqualTo(String value) {
            addCriterion("INFO_PKID <=", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLike(String value) {
            addCriterion("INFO_PKID like", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotLike(String value) {
            addCriterion("INFO_PKID not like", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIn(List<String> values) {
            addCriterion("INFO_PKID in", values, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotIn(List<String> values) {
            addCriterion("INFO_PKID not in", values, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidBetween(String value1, String value2) {
            addCriterion("INFO_PKID between", value1, value2, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotBetween(String value1, String value2) {
            addCriterion("INFO_PKID not between", value1, value2, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(String value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(String value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(String value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(String value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(String value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLike(String value) {
            addCriterion("INFO_ID like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotLike(String value) {
            addCriterion("INFO_ID not like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<String> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<String> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(String value1, String value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(String value1, String value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNull() {
            addCriterion("INFO_NAME is null");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNotNull() {
            addCriterion("INFO_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andInfoNameEqualTo(String value) {
            addCriterion("INFO_NAME =", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotEqualTo(String value) {
            addCriterion("INFO_NAME <>", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThan(String value) {
            addCriterion("INFO_NAME >", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_NAME >=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThan(String value) {
            addCriterion("INFO_NAME <", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThanOrEqualTo(String value) {
            addCriterion("INFO_NAME <=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLike(String value) {
            addCriterion("INFO_NAME like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotLike(String value) {
            addCriterion("INFO_NAME not like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameIn(List<String> values) {
            addCriterion("INFO_NAME in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotIn(List<String> values) {
            addCriterion("INFO_NAME not in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameBetween(String value1, String value2) {
            addCriterion("INFO_NAME between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotBetween(String value1, String value2) {
            addCriterion("INFO_NAME not between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagIsNull() {
            addCriterion("FIRST_APPOINT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagIsNotNull() {
            addCriterion("FIRST_APPOINT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagEqualTo(String value) {
            addCriterion("FIRST_APPOINT_FLAG =", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagNotEqualTo(String value) {
            addCriterion("FIRST_APPOINT_FLAG <>", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagGreaterThan(String value) {
            addCriterion("FIRST_APPOINT_FLAG >", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_APPOINT_FLAG >=", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagLessThan(String value) {
            addCriterion("FIRST_APPOINT_FLAG <", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagLessThanOrEqualTo(String value) {
            addCriterion("FIRST_APPOINT_FLAG <=", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagLike(String value) {
            addCriterion("FIRST_APPOINT_FLAG like", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagNotLike(String value) {
            addCriterion("FIRST_APPOINT_FLAG not like", value, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagIn(List<String> values) {
            addCriterion("FIRST_APPOINT_FLAG in", values, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagNotIn(List<String> values) {
            addCriterion("FIRST_APPOINT_FLAG not in", values, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagBetween(String value1, String value2) {
            addCriterion("FIRST_APPOINT_FLAG between", value1, value2, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andFirstAppointFlagNotBetween(String value1, String value2) {
            addCriterion("FIRST_APPOINT_FLAG not between", value1, value2, "firstAppointFlag");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidIsNull() {
            addCriterion("SEND_WORKTILE_PART_PKID is null");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidIsNotNull() {
            addCriterion("SEND_WORKTILE_PART_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidEqualTo(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID =", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidNotEqualTo(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID <>", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidGreaterThan(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID >", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID >=", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidLessThan(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID <", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidLessThanOrEqualTo(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID <=", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidLike(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID like", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidNotLike(String value) {
            addCriterion("SEND_WORKTILE_PART_PKID not like", value, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidIn(List<String> values) {
            addCriterion("SEND_WORKTILE_PART_PKID in", values, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidNotIn(List<String> values) {
            addCriterion("SEND_WORKTILE_PART_PKID not in", values, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidBetween(String value1, String value2) {
            addCriterion("SEND_WORKTILE_PART_PKID between", value1, value2, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andSendWorktilePartPkidNotBetween(String value1, String value2) {
            addCriterion("SEND_WORKTILE_PART_PKID not between", value1, value2, "sendWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidIsNull() {
            addCriterion("RECV_WORKTILE_PART_PKID is null");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidIsNotNull() {
            addCriterion("RECV_WORKTILE_PART_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidEqualTo(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID =", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidNotEqualTo(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID <>", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidGreaterThan(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID >", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidGreaterThanOrEqualTo(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID >=", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidLessThan(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID <", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidLessThanOrEqualTo(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID <=", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidLike(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID like", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidNotLike(String value) {
            addCriterion("RECV_WORKTILE_PART_PKID not like", value, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidIn(List<String> values) {
            addCriterion("RECV_WORKTILE_PART_PKID in", values, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidNotIn(List<String> values) {
            addCriterion("RECV_WORKTILE_PART_PKID not in", values, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidBetween(String value1, String value2) {
            addCriterion("RECV_WORKTILE_PART_PKID between", value1, value2, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktilePartPkidNotBetween(String value1, String value2) {
            addCriterion("RECV_WORKTILE_PART_PKID not between", value1, value2, "recvWorktilePartPkid");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagIsNull() {
            addCriterion("RECV_WORKTILE_EXEC_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagIsNotNull() {
            addCriterion("RECV_WORKTILE_EXEC_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagEqualTo(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG =", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagNotEqualTo(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG <>", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagGreaterThan(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG >", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagGreaterThanOrEqualTo(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG >=", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagLessThan(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG <", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagLessThanOrEqualTo(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG <=", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagLike(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG like", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagNotLike(String value) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG not like", value, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagIn(List<String> values) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG in", values, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagNotIn(List<String> values) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG not in", values, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagBetween(String value1, String value2) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG between", value1, value2, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andRecvWorktileExecFlagNotBetween(String value1, String value2) {
            addCriterion("RECV_WORKTILE_EXEC_FLAG not between", value1, value2, "recvWorktileExecFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagIsNull() {
            addCriterion("ARCHIVED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagIsNotNull() {
            addCriterion("ARCHIVED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagEqualTo(String value) {
            addCriterion("ARCHIVED_FLAG =", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagNotEqualTo(String value) {
            addCriterion("ARCHIVED_FLAG <>", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagGreaterThan(String value) {
            addCriterion("ARCHIVED_FLAG >", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ARCHIVED_FLAG >=", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagLessThan(String value) {
            addCriterion("ARCHIVED_FLAG <", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagLessThanOrEqualTo(String value) {
            addCriterion("ARCHIVED_FLAG <=", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagLike(String value) {
            addCriterion("ARCHIVED_FLAG like", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagNotLike(String value) {
            addCriterion("ARCHIVED_FLAG not like", value, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagIn(List<String> values) {
            addCriterion("ARCHIVED_FLAG in", values, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagNotIn(List<String> values) {
            addCriterion("ARCHIVED_FLAG not in", values, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagBetween(String value1, String value2) {
            addCriterion("ARCHIVED_FLAG between", value1, value2, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andArchivedFlagNotBetween(String value1, String value2) {
            addCriterion("ARCHIVED_FLAG not between", value1, value2, "archivedFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameIsNull() {
            addCriterion("CREATED_BY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameIsNotNull() {
            addCriterion("CREATED_BY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameEqualTo(String value) {
            addCriterion("CREATED_BY_NAME =", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameNotEqualTo(String value) {
            addCriterion("CREATED_BY_NAME <>", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameGreaterThan(String value) {
            addCriterion("CREATED_BY_NAME >", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY_NAME >=", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameLessThan(String value) {
            addCriterion("CREATED_BY_NAME <", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY_NAME <=", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameLike(String value) {
            addCriterion("CREATED_BY_NAME like", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameNotLike(String value) {
            addCriterion("CREATED_BY_NAME not like", value, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameIn(List<String> values) {
            addCriterion("CREATED_BY_NAME in", values, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameNotIn(List<String> values) {
            addCriterion("CREATED_BY_NAME not in", values, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameBetween(String value1, String value2) {
            addCriterion("CREATED_BY_NAME between", value1, value2, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedByNameNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY_NAME not between", value1, value2, "createdByName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(String value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(String value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(String value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(String value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLike(String value) {
            addCriterion("CREATED_TIME like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotLike(String value) {
            addCriterion("CREATED_TIME not like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<String> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<String> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(String value1, String value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(String value1, String value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRecVersionIsNull() {
            addCriterion("REC_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecVersionIsNotNull() {
            addCriterion("REC_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecVersionEqualTo(Integer value) {
            addCriterion("REC_VERSION =", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionNotEqualTo(Integer value) {
            addCriterion("REC_VERSION <>", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionGreaterThan(Integer value) {
            addCriterion("REC_VERSION >", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("REC_VERSION >=", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionLessThan(Integer value) {
            addCriterion("REC_VERSION <", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionLessThanOrEqualTo(Integer value) {
            addCriterion("REC_VERSION <=", value, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionIn(List<Integer> values) {
            addCriterion("REC_VERSION in", values, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionNotIn(List<Integer> values) {
            addCriterion("REC_VERSION not in", values, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionBetween(Integer value1, Integer value2) {
            addCriterion("REC_VERSION between", value1, value2, "recVersion");
            return (Criteria) this;
        }

        public Criteria andRecVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("REC_VERSION not between", value1, value2, "recVersion");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("TID is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("TID is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(String value) {
            addCriterion("TID =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(String value) {
            addCriterion("TID <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(String value) {
            addCriterion("TID >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(String value) {
            addCriterion("TID >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(String value) {
            addCriterion("TID <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(String value) {
            addCriterion("TID <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLike(String value) {
            addCriterion("TID like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotLike(String value) {
            addCriterion("TID not like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<String> values) {
            addCriterion("TID in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<String> values) {
            addCriterion("TID not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(String value1, String value2) {
            addCriterion("TID between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(String value1, String value2) {
            addCriterion("TID not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andOperTypeIsNull() {
            addCriterion("OPER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperTypeIsNotNull() {
            addCriterion("OPER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperTypeEqualTo(String value) {
            addCriterion("OPER_TYPE =", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeNotEqualTo(String value) {
            addCriterion("OPER_TYPE <>", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeGreaterThan(String value) {
            addCriterion("OPER_TYPE >", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TYPE >=", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeLessThan(String value) {
            addCriterion("OPER_TYPE <", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TYPE <=", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeLike(String value) {
            addCriterion("OPER_TYPE like", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeNotLike(String value) {
            addCriterion("OPER_TYPE not like", value, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeIn(List<String> values) {
            addCriterion("OPER_TYPE in", values, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeNotIn(List<String> values) {
            addCriterion("OPER_TYPE not in", values, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeBetween(String value1, String value2) {
            addCriterion("OPER_TYPE between", value1, value2, "operType");
            return (Criteria) this;
        }

        public Criteria andOperTypeNotBetween(String value1, String value2) {
            addCriterion("OPER_TYPE not between", value1, value2, "operType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 13 14:57:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}