package worktile.repository.model;

public class Worktile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.ID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.SUBJECT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.CONTENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.START_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.END_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.ATTACHMENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE.DEPT_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String deptPkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.PKID
     *
     * @return the value of WORKTILE.WORKTILE.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.PKID
     *
     * @param pkid the value for WORKTILE.WORKTILE.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.ID
     *
     * @return the value of WORKTILE.WORKTILE.ID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.ID
     *
     * @param id the value for WORKTILE.WORKTILE.ID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.SUBJECT
     *
     * @return the value of WORKTILE.WORKTILE.SUBJECT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.SUBJECT
     *
     * @param subject the value for WORKTILE.WORKTILE.SUBJECT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.CONTENT
     *
     * @return the value of WORKTILE.WORKTILE.CONTENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.CONTENT
     *
     * @param content the value for WORKTILE.WORKTILE.CONTENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.START_TIME
     *
     * @return the value of WORKTILE.WORKTILE.START_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.START_TIME
     *
     * @param startTime the value for WORKTILE.WORKTILE.START_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.END_TIME
     *
     * @return the value of WORKTILE.WORKTILE.END_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.END_TIME
     *
     * @param endTime the value for WORKTILE.WORKTILE.END_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.ATTACHMENT
     *
     * @return the value of WORKTILE.WORKTILE.ATTACHMENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.ATTACHMENT
     *
     * @param attachment the value for WORKTILE.WORKTILE.ATTACHMENT
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.ARCHIVED_FLAG
     *
     * @return the value of WORKTILE.WORKTILE.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for WORKTILE.WORKTILE.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.CREATED_BY
     *
     * @return the value of WORKTILE.WORKTILE.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.CREATED_BY
     *
     * @param createdBy the value for WORKTILE.WORKTILE.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.CREATED_TIME
     *
     * @return the value of WORKTILE.WORKTILE.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.CREATED_TIME
     *
     * @param createdTime the value for WORKTILE.WORKTILE.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.LAST_UPD_BY
     *
     * @return the value of WORKTILE.WORKTILE.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.LAST_UPD_BY
     *
     * @param lastUpdBy the value for WORKTILE.WORKTILE.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.LAST_UPD_TIME
     *
     * @return the value of WORKTILE.WORKTILE.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for WORKTILE.WORKTILE.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.REMARK
     *
     * @return the value of WORKTILE.WORKTILE.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.REMARK
     *
     * @param remark the value for WORKTILE.WORKTILE.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.REC_VERSION
     *
     * @return the value of WORKTILE.WORKTILE.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.REC_VERSION
     *
     * @param recVersion the value for WORKTILE.WORKTILE.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.TID
     *
     * @return the value of WORKTILE.WORKTILE.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.TID
     *
     * @param tid the value for WORKTILE.WORKTILE.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE.DEPT_PKID
     *
     * @return the value of WORKTILE.WORKTILE.DEPT_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getDeptPkid() {
        return deptPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE.DEPT_PKID
     *
     * @param deptPkid the value for WORKTILE.WORKTILE.DEPT_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setDeptPkid(String deptPkid) {
        this.deptPkid = deptPkid == null ? null : deptPkid.trim();
    }
}