package worktile.repository.model;

public class WorktileAppoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.INFO_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String infoPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.RECV_PART_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String recvPartPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.RECV_EXEC_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String recvExecFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKTILE.WORKTILE_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.PKID
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.PKID
     *
     * @param pkid the value for WORKTILE.WORKTILE_APPOINT.PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.INFO_PKID
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.INFO_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getInfoPkid() {
        return infoPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.INFO_PKID
     *
     * @param infoPkid the value for WORKTILE.WORKTILE_APPOINT.INFO_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setInfoPkid(String infoPkid) {
        this.infoPkid = infoPkid == null ? null : infoPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.RECV_PART_PKID
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.RECV_PART_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getRecvPartPkid() {
        return recvPartPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.RECV_PART_PKID
     *
     * @param recvPartPkid the value for WORKTILE.WORKTILE_APPOINT.RECV_PART_PKID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRecvPartPkid(String recvPartPkid) {
        this.recvPartPkid = recvPartPkid == null ? null : recvPartPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.RECV_EXEC_FLAG
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.RECV_EXEC_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getRecvExecFlag() {
        return recvExecFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.RECV_EXEC_FLAG
     *
     * @param recvExecFlag the value for WORKTILE.WORKTILE_APPOINT.RECV_EXEC_FLAG
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRecvExecFlag(String recvExecFlag) {
        this.recvExecFlag = recvExecFlag == null ? null : recvExecFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.CREATED_BY
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.CREATED_BY
     *
     * @param createdBy the value for WORKTILE.WORKTILE_APPOINT.CREATED_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.CREATED_TIME
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.CREATED_TIME
     *
     * @param createdTime the value for WORKTILE.WORKTILE_APPOINT.CREATED_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_BY
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_BY
     *
     * @param lastUpdBy the value for WORKTILE.WORKTILE_APPOINT.LAST_UPD_BY
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_TIME
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for WORKTILE.WORKTILE_APPOINT.LAST_UPD_TIME
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.REMARK
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.REMARK
     *
     * @param remark the value for WORKTILE.WORKTILE_APPOINT.REMARK
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.REC_VERSION
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.REC_VERSION
     *
     * @param recVersion the value for WORKTILE.WORKTILE_APPOINT.REC_VERSION
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKTILE.WORKTILE_APPOINT.TID
     *
     * @return the value of WORKTILE.WORKTILE_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKTILE.WORKTILE_APPOINT.TID
     *
     * @param tid the value for WORKTILE.WORKTILE_APPOINT.TID
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}