package worktile.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import worktile.repository.model.Oper;
import worktile.repository.model.OperExample;

public interface OperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int countByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int deleteByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int insert(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int insertSelective(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    List<Oper> selectByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    Oper selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") Oper record, @Param("example") OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int updateByExample(@Param("record") Oper record, @Param("example") OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int updateByPrimaryKeySelective(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.OPER
     *
     * @mbggenerated Wed Feb 25 14:09:20 CST 2015
     */
    int updateByPrimaryKey(Oper record);
}