package worktile.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import worktile.repository.model.RsTidKeys;
import worktile.repository.model.RsTidKeysExample;

public interface RsTidKeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int countByExample(RsTidKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int deleteByExample(RsTidKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int insert(RsTidKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int insertSelective(RsTidKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    List<RsTidKeys> selectByExample(RsTidKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    RsTidKeys selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") RsTidKeys record, @Param("example") RsTidKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int updateByExample(@Param("record") RsTidKeys record, @Param("example") RsTidKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int updateByPrimaryKeySelective(RsTidKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK.RS_TID_KEYS
     *
     * @mbggenerated Mon Mar 02 13:49:41 CST 2015
     */
    int updateByPrimaryKey(RsTidKeys record);
}