package worktile.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import worktile.repository.model.WorktileAppointHis;
import worktile.repository.model.WorktileAppointHisExample;

public interface WorktileAppointHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int countByExample(WorktileAppointHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int deleteByExample(WorktileAppointHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int insert(WorktileAppointHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int insertSelective(WorktileAppointHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    List<WorktileAppointHis> selectByExample(WorktileAppointHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    WorktileAppointHis selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") WorktileAppointHis record, @Param("example") WorktileAppointHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByExample(@Param("record") WorktileAppointHis record, @Param("example") WorktileAppointHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByPrimaryKeySelective(WorktileAppointHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE_APPOINT_HIS
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByPrimaryKey(WorktileAppointHis record);
}