package worktile.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import worktile.repository.model.Worktile;
import worktile.repository.model.WorktileExample;

public interface WorktileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int countByExample(WorktileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int deleteByExample(WorktileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int insert(Worktile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int insertSelective(Worktile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    List<Worktile> selectByExample(WorktileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    Worktile selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") Worktile record, @Param("example") WorktileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByExample(@Param("record") Worktile record, @Param("example") WorktileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByPrimaryKeySelective(Worktile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKTILE.WORKTILE
     *
     * @mbggenerated Fri Mar 13 14:57:38 CST 2015
     */
    int updateByPrimaryKey(Worktile record);
}